# Generated by Django 6.0.3 on 2026-04-16 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='backorder',
        ),
        migrations.AlterField(
            model_name='material',
            name='leadtime',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='material',
            name='on_hand',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
